### ISSUE TITLE
Different names in Package.swift and Podfile

### ISSUE THREAD

**Issue by jnewc** [onevcat/Rainbow#13]
The inconsistency in naming (Rainbow / RainbowSwift) makes it difficult to build the same project using Xcode and SPM, without editing imports to one or the other.

**Comment by onevcat** [comment]
Why do you need to build it with both SPM and CocoaPods?

**Comment by jnewc** [comment]
I'm generating code coverage data with Xcode but building and running with SPM.

**Comment by onevcat** [comment]
Since the name of `Rainbow` is already taken by another framework in the central CocoaPods repo, so we could not use that name anymore.

A workaround would be copying the [podspec file](https://github.com/onevcat/Rainbow/blob/master/RainbowSwift.podspec) to your own project, modifying the `s.name` from "RainbowSwift" to "Rainbow" and then use your own podspec to integrate:

```ruby
pod 'Rainbow', :podspec => 'https://your-repo.com/Rainbow.podspec'
```
